//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class get_All_QuestionTF
    {
        public int Quest_ID { get; set; }
        public string Quest_Description { get; set; }
        public Nullable<int> Quest_Answer { get; set; }
        public Nullable<bool> Quest_Type { get; set; }
    }
}
