//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Topic_ID { get; set; }
        public string Topic_name { get; set; }
        public Nullable<int> Course_ID { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
